name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: gh repo list sanand0 --limit 1000 --json name,createdAt,pushedAt,description,repositoryTopics,visibility > .repos.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node update.js
      - run: rm -f .repos.json
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@v4
